apiVersion: v1
kind: Service
metadata:
  labels:
    app: mywebsvc
  name: {{.Values.svc.name }}
spec:
  ports:
  - name: "80"
    port: {{.Values.svc.port }}
    protocol: {{.Values.svc.protocol }}
    targetPort: {{.Values.svc.targetPort }}
  selector:
    run: nginx
  type: {{.Values.svc.type }}